#for windows  copy .env.example .env && npm run genkey for mac or linux cp .env.example .env && npm run genkey

services:
  smart-contract-deployer:
    build: .
    image: besu-contract-deployer:latest
    container_name: contract-deployer
    env_file:
      - .env
    environment:
      RPC_URL: http://validator1:8545
    volumes:
      - ../app:/app_config
    networks:
      - besu-net

networks:
  besu-net:
    name: blockchain-network_besu-net
    external: true