version: '3.8'

services:
  backend-api:
    image: besu-backend-api:latest
    build: .
    container_name: backend-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
