version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres_db
    environment:
      POSTGRES_USER: tarik
      POSTGRES_PASSWORD: ayb
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
