services:
  postgres:
    build: .
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - besu-net

volumes:
  postgres_data:

networks:
  besu-net:
    name: blockchain-network_besu-net
    external: true
